/*
 * Parameters for 1 arc-second high resolution mode of operation
 * Generated by ./configure by amusselm on Sat Jul 7 16:34:52 PDT 2012
 * Modified by hand as part of the OpenCL reconfigureing...
 * Andrew J. Musselman, KI6UOC
*/
#define HD_MODE 1
#define MAXPAGES 4

struct site {	
   double lat;
   double lon;
   float alt;
   char name[50];
   char filename[255];
} site;

/**
 * Represents the terrain data, and keeps track of which points have already been
 * calculated
 */
struct dem {	
   int min_north;
   int max_north;
   int min_west;
   int max_west;
   int max_el;
   int min_el;
   short data[IPPD][IPPD];
   unsigned char mask[IPPD][IPPD];
   unsigned char signal[IPPD][IPPD];
}	

/**
 * Stores the Longely-Rice paramaters
 */
struct LR {	
   double eps_dielect; 
   double sgm_conductivity; 
   double eno_ns_surfref;
   double frq_mhz; 
   double conf; 
   double rel;
   double erp;
   int radio_climate;  
   int pol;
   float antenna_pattern[361][1001];
}
